'use client';

import { useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, Building2, CalendarDays, Check, CircleDollarSign, ClipboardList, Download, FileText, Menu, Plus, Search, Settings2, Truck, X } from 'lucide-react';
import { useSimulatedData } from '@/hooks/useSimulatedData';
import { useLocalStorage } from '@/hooks/useLocalStorage';
import type { DriverRecord, FinancialInput, Provider, VehicleClass } from '@/lib/types';
import { resizeVehicleFleet } from '@/lib/fleetModel';
import { buildProjection, calculateDailyMetrics, toDateString, type DailyRecord } from '@/lib/operationsReporting';
import { exportBusinessModelExcel, exportDailyReportPdf } from '@/lib/reportExport';

type View = 'summary' | 'drivers' | 'fleet' | 'customers' | 'costs' | 'daily' | 'risks' | 'actions';
type NumberField = keyof Pick<FinancialInput,
  'companyDriverCount' | 'driverSalary' | 'opsTeamCount' | 'opsTeamAvgSalary' | 'salesTeamCount' |
  'salesTeamBaseSalary' | 'warehouseStaff' | 'warehouseStaffSalary' | 'warehouseRent' |
  'warehouseUtilities' | 'officeRent' | 'internetCost' | 'electricityCost' | 'technologySaaS' |
  'marketingBudget' | 'accountingLegal' | 'miscExpenses' | 'packagingCostPerUnit' |
  'pickPackLaborPerOrder' | 'labelsAndDocs' | 'returnLogisticsCost' | 'failedDeliveryRate' |
  'failedDeliveryCost' | 'returnRate' | 'clientPaymentDelay' | 'fuelPricePerLiter'
>;

const NAV = [
  { id: 'summary' as const, label: 'Summary', icon: BarChart3 },
  { id: 'fleet' as const, label: 'Cars & drivers', icon: Truck },
  { id: 'customers' as const, label: 'Customers & revenue', icon: Building2 },
  { id: 'costs' as const, label: 'Company costs', icon: CircleDollarSign },
  { id: 'daily' as const, label: 'Daily report', icon: CalendarDays },
  { id: 'risks' as const, label: 'Risks', icon: AlertTriangle },
  { id: 'actions' as const, label: 'Follow-up', icon: ClipboardList },
];

const money = (value: number, digits = 0) => new Intl.NumberFormat('en-SA', { style: 'currency', currency: 'SAR', maximumFractionDigits: digits }).format(value);
const num = (value: number) => new Intl.NumberFormat('en-SA').format(Math.round(value));

export default function BusinessModelApp() {
  const { financialInput: input, financialOutput: output, updateFinancialInput, setVehicleClasses, setProviders, setDrivers, addVehicleClass, addProvider } = useSimulatedData();
  const [view, setView] = useState<View>('summary');
  const [mobileNav, setMobileNav] = useState(false);
  const [search, setSearch] = useState('');
  const [dailyRecords, setDailyRecords] = useLocalStorage<Record<string, DailyRecord>>('vega-daily-reports-v2', {});
  const [actions, setActions] = useState([
    { id: 1, text: 'Validate each customer price against cost per shipment', owner: 'Commercial', done: false },
    { id: 2, text: 'Confirm actual monthly payroll and headcount', owner: 'Finance', done: false },
    { id: 3, text: 'Reconcile vehicle rent and fuel assumptions', owner: 'Operations', done: false },
  ]);

  const fleetCount = input.vehicleClasses.filter(item => item.enabled).reduce((sum, item) => sum + item.quantity, 0);
  const driverGap = input.companyDriverCount - fleetCount;
  const contribution = output.avgRevenuePerShipment - output.costBreakdown.perShipment / Math.max(1, output.totalMonthlyShipments);
  const risks = useMemo(() => [
    { level: output.netMargin < 0 ? 'Critical' : 'Controlled', title: 'Profitability', value: `${output.netMarginPercent.toFixed(1)}% margin`, detail: output.netMargin < 0 ? `Monthly loss of ${money(Math.abs(output.netMargin))}.` : `Monthly profit of ${money(output.netMargin)}.` },
    { level: driverGap < 0 ? 'High' : 'Controlled', title: 'Driver coverage', value: `${input.companyDriverCount} drivers / ${fleetCount} vehicles`, detail: driverGap < 0 ? `${Math.abs(driverGap)} vehicles have no company driver in the model.` : `${driverGap} drivers above fleet count.` },
    { level: output.avgRevenuePerShipment < output.costPerShipment ? 'Critical' : 'Controlled', title: 'Unit economics', value: `${money(output.avgRevenuePerShipment, 2)} revenue vs ${money(output.costPerShipment, 2)} cost`, detail: 'Scaling volume is unsafe while average revenue remains below total unit cost.' },
    { level: input.clientPaymentDelay > 30 ? 'High' : 'Controlled', title: 'Cash collection', value: `${input.clientPaymentDelay} days`, detail: `Estimated runway: ${output.cashRunway.toFixed(1)} months.` },
  ], [driverGap, fleetCount, input.clientPaymentDelay, input.companyDriverCount, output]);

  const setNumber = (field: NumberField, raw: string) => updateFinancialInput({ [field]: Math.max(0, Number(raw) || 0) });
  const changeVehicle = (id: string, patch: Partial<VehicleClass>) => {
    let nextTotal = fleetCount;
    setVehicleClasses(rows => {
      const next = rows.map(row => row.id === id ? { ...row, ...patch } : row);
      nextTotal = next.filter(row => row.enabled).reduce((sum, row) => sum + row.quantity, 0);
      return next;
    });
    updateFinancialInput({ companyDriverCount: nextTotal });
  };
  const changeProvider = (id: string, patch: Partial<Provider>) => setProviders(rows => rows.map(row => row.id === id ? { ...row, ...patch } : row));
  const changeDriver = (id: string, patch: Partial<DriverRecord>) => setDrivers(rows => rows.map(row => row.id === id ? { ...row, ...patch } : row));
  const removeVehicle = (id: string) => {
    let nextTotal = fleetCount;
    setVehicleClasses(rows => {
      const next = rows.filter(item => item.id !== id);
      nextTotal = next.filter(row => row.enabled).reduce((sum, row) => sum + row.quantity, 0);
      return next;
    });
    updateFinancialInput({ companyDriverCount: nextTotal });
  };
  const setFleetCount = (raw: string) => {
    const target = Math.max(0, Math.round(Number(raw) || 0));
    setVehicleClasses(rows => resizeVehicleFleet(rows, target));
    updateFinancialInput({ companyDriverCount: target });
  };
  const selectView = (next: View) => { setView(next === 'drivers' ? 'fleet' : next); setMobileNav(false); };

  return <div className="bm-app">
    <a className="bm-skip" href="#bm-main">Skip to main content</a>
    {mobileNav && <button className="bm-scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <aside className={`bm-sidebar ${mobileNav ? 'open' : ''}`}>
      <div className="bm-brand"><div><strong>VEGA</strong><span>Business model</span></div><button aria-label="Close navigation" onClick={() => setMobileNav(false)}><X size={18} /></button></div>
      <nav aria-label="Business model sections">{NAV.map(item => { const Icon = item.icon; return <button key={item.id} className={view === item.id ? 'active' : ''} aria-current={view === item.id ? 'page' : undefined} onClick={() => selectView(item.id)}><Icon size={16} /><span>{item.label}</span>{item.id === 'risks' && <em>{risks.filter(r => r.level !== 'Controlled').length}</em>}</button>; })}</nav>
      <div className="bm-source"><span>Saved in this browser</span><small>No map, telematics, or accounting connection</small></div>
    </aside>

    <div className="bm-shell">
      <header className="bm-top"><button className="bm-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={19} /></button><div><strong>{NAV.find(item => item.id === view)?.label}</strong><span>All figures recalculate from your inputs</span></div><div className="bm-search"><Search size={14}/><input aria-label="Search app" placeholder="Search pages, drivers, customers" value={search} onChange={event=>setSearch(event.target.value)}/>{search&&<div className="bm-search-results">{NAV.filter(item=>item.label.toLowerCase().includes(search.toLowerCase())).map(item=><button key={item.id} onClick={()=>{selectView(item.id);setSearch('');}}>{item.label}</button>)}{input.drivers.filter(driver=>driver.fullName.toLowerCase().includes(search.toLowerCase())).map(driver=><button key={driver.id} onClick={()=>{selectView('fleet');setSearch('');}}>Driver: {driver.fullName}</button>)}{input.providers.filter(provider=>provider.name.toLowerCase().includes(search.toLowerCase())).map(provider=><button key={provider.id} onClick={()=>{selectView('customers');setSearch('');}}>Customer: {provider.name}</button>)}</div>}</div><div className="bm-status"><i /> Local model</div></header>
      <main id="bm-main" className="bm-main">
        {view === 'summary' && <CoreSummary output={output} input={input} fleetCount={fleetCount} driverGap={driverGap} contribution={contribution} risks={risks} onNavigate={selectView} dailyRecords={dailyRecords} />}
        {view === 'fleet' && <Page title="Cars & drivers" description="One car equals one driver. Changing either vehicle quantity or the total keeps both synchronized."><div className="bm-form-card bm-combined-count"><NumberInput label="Cars & drivers" value={fleetCount} onChange={setFleetCount} suffix="cars + drivers" /><Readout label="Driver payroll / month" value={money(fleetCount * input.driverSalary)} /></div><EditableTable columns={['Vehicle type','Cars & drivers','Rent / month','Insurance + maintenance','Fuel efficiency','Distance / day','']}>
          {input.vehicleClasses.map(row => <div className="bm-table-row bm-fleet-row" key={row.id}><TextInput ariaLabel="Vehicle type" value={row.name} onChange={value => changeVehicle(row.id,{name:value})} /><CellNumber ariaLabel={`${row.name} quantity`} value={row.quantity} onChange={value => changeVehicle(row.id,{quantity:value})} /><CellNumber ariaLabel={`${row.name} monthly rent`} value={row.monthlyRent} onChange={value => changeVehicle(row.id,{monthlyRent:value})} /><CellNumber ariaLabel={`${row.name} overhead`} value={row.variableCost} onChange={value => changeVehicle(row.id,{variableCost:value})} /><CellNumber ariaLabel={`${row.name} fuel efficiency`} value={row.fuelEfficiency} onChange={value => changeVehicle(row.id,{fuelEfficiency:value})} /><CellNumber ariaLabel={`${row.name} daily distance`} value={row.avgDailyDistance} onChange={value => changeVehicle(row.id,{avgDailyDistance:value})} /><button className="bm-remove" aria-label={`Remove ${row.name}`} onClick={() => removeVehicle(row.id)}>Remove</button></div>)}
        </EditableTable><button className="bm-add" onClick={addVehicleClass}><Plus size={15}/> Add vehicle type</button><div className="bm-inline-total"><span>Synchronized total</span><strong>{fleetCount} cars + {input.companyDriverCount} drivers</strong><span>Monthly fleet cost</span><strong>{money(output.fleetMonthlyCost)}</strong></div><div className="bm-roster"><div className="bm-roster-head"><h2>Driver roster</h2><span>{input.drivers.length} drivers</span></div><EditableTable columns={['Driver name','Phone','Assigned vehicle','Status']}>{input.drivers.map(driver => <div className="bm-table-row bm-driver-row" key={driver.id}><TextInput ariaLabel={`${driver.id} driver name`} value={driver.fullName} onChange={value => changeDriver(driver.id,{fullName:value})} /><TextInput ariaLabel={`${driver.fullName} phone`} value={driver.phone} onChange={value => changeDriver(driver.id,{phone:value})} /><select aria-label={`${driver.fullName} assigned vehicle`} value={driver.assignedVehicle} onChange={event => changeDriver(driver.id,{assignedVehicle:event.target.value})}>{input.vehicleClasses.map(vehicle => <option key={vehicle.id} value={vehicle.name}>{vehicle.name}</option>)}</select><select aria-label={`${driver.fullName} status`} value={driver.status} onChange={event => changeDriver(driver.id,{status:event.target.value as DriverRecord['status']})}><option value="active">Active</option><option value="inactive">Inactive</option></select></div>)}</EditableTable></div></Page>}
        {view === 'customers' && <Page title="Customers & revenue" description="Enter contracted daily volume and the price your company receives for each delivery."><EditableTable columns={['Customer / contract','Shipments / day','Price / shipment','Monthly revenue','']}>
          {input.providers.map(row => { const evaluation = output.providerEvaluations.find(item => item.id === row.id); return <div className="bm-table-row bm-customer-row" key={row.id}><TextInput ariaLabel="Customer name" value={row.name} onChange={value => changeProvider(row.id,{name:value})} /><CellNumber ariaLabel={`${row.name} shipments per day`} value={row.shipmentsPerDay} onChange={value => changeProvider(row.id,{shipmentsPerDay:value})} /><CellNumber ariaLabel={`${row.name} price per shipment`} value={row.pricePerShipment} onChange={value => changeProvider(row.id,{pricePerShipment:value})} step="0.1" /><strong>{money(evaluation?.monthlyRevenue ?? 0)}</strong><button className="bm-remove" aria-label={`Remove ${row.name}`} onClick={() => setProviders(rows => rows.filter(item => item.id !== row.id))}>Remove</button></div>})}
        </EditableTable><button className="bm-add" onClick={addProvider}><Plus size={15}/> Add customer</button></Page>}
        {view === 'costs' && <Page title="Company costs" description="All monetary assumptions are here. Replace every default with your actual payroll, lease, fuel, and supplier costs."><CostSections input={input} output={output} setNumber={setNumber} changeVehicle={changeVehicle} /></Page>}
        {view === 'daily' && <DailyReport input={input} output={output} records={dailyRecords} setRecords={setDailyRecords} />}
        {view === 'risks' && <Page title="Risks" description="These flags are rules based on your entered numbers—not AI predictions."><div className="bm-risk-table"><div className="bm-risk-head"><span>Status</span><span>Risk</span><span>Current value</span><span>Reason</span></div>{risks.map(risk => <div className="bm-risk-row" key={risk.title}><span className={risk.level === 'Controlled' ? 'ok' : 'bad'}>{risk.level}</span><strong>{risk.title}</strong><span>{risk.value}</span><p>{risk.detail}</p></div>)}</div></Page>}
        {view === 'actions' && <Page title="Follow-up" description="A small working list for validating the model. Completed items stay for this session."><div className="bm-actions">{actions.map(action => <div className={action.done ? 'done' : ''} key={action.id}><button aria-label={action.done ? `Reopen ${action.text}` : `Complete ${action.text}`} onClick={() => setActions(rows => rows.map(row => row.id === action.id ? {...row,done:!row.done}:row))}>{action.done ? <Check size={15}/> : null}</button><span><strong>{action.text}</strong><small>{action.owner}</small></span></div>)}</div></Page>}
      </main>
    </div>
  </div>;
}

function Page({ title, description, children }: { title:string; description:string; children:React.ReactNode }) { return <><div className="bm-page-head"><h1>{title}</h1><p>{description}</p></div>{children}</>; }
function CoreSummary({ output,input,fleetCount,driverGap,contribution,risks,onNavigate,dailyRecords }: { output:ReturnType<typeof useSimulatedData>['financialOutput']; input:FinancialInput; fleetCount:number; driverGap:number; contribution:number; risks:{level:string;title:string;value:string;detail:string}[]; onNavigate:(view:View)=>void; dailyRecords:Record<string,DailyRecord> }) {
  const trend=buildProjection(output,14,dailyRecords);
  const categories=Object.entries(output.costBreakdown).filter(([key])=>!['costPerShipment','total'].includes(key)) as [string,number][];
  const shipmentsPerCar=output.totalDailyShipments/Math.max(1,fleetCount);
  const activeRisks=risks.filter(risk=>risk.level!=='Controlled');
  return <><div className="bm-page-head bm-summary-head"><div><h1>Operations & financial overview</h1><p>Useful operating indicators from your inputs. Dashed points are model projections; saved daily reports are actual records.</p></div><div className="bm-head-actions"><button onClick={()=>onNavigate('daily')}><FileText size={15}/> Record today</button><button onClick={()=>onNavigate('costs')}><Settings2 size={15}/> Edit company costs</button></div></div>
    <section className="bm-kpis bm-decision-kpis"><Kpi label="Monthly revenue" value={money(output.totalRevenue)} /><Kpi label="Monthly profit / loss" value={money(output.netMargin)} tone={output.netMargin<0?'bad':'good'} /><Kpi label="Margin" value={`${output.netMarginPercent.toFixed(1)}%`} tone={output.netMargin<0?'bad':'good'} /><Kpi label="Break-even volume" value={`${num(output.operationalBreakeven)} / month`} /></section>
    <div className="bm-dashboard-grid"><TrendChart data={trend}/><section className="bm-panel bm-unit-card"><div className="bm-panel-head"><div><span>Unit economics</span><h2>What each shipment produces</h2></div></div><div className="bm-unit-values"><Metric label="Revenue / shipment" value={money(output.avgRevenuePerShipment,2)}/><Metric label="Cost / shipment" value={money(output.costPerShipment,2)}/><Metric label="Profit / shipment" value={money(output.avgRevenuePerShipment-output.costPerShipment,2)} tone={output.avgRevenuePerShipment<output.costPerShipment?'bad':'good'}/><Metric label="Shipments / car / day" value={shipmentsPerCar.toFixed(1)}/></div><button className="bm-link-button" onClick={()=>onNavigate('customers')}>Review customer pricing</button></section></div>
    <div className="bm-dashboard-grid"><CostChart categories={categories} total={output.totalCost}/><section className="bm-panel bm-watch-card"><div className="bm-panel-head"><div><span>Management attention</span><h2>{activeRisks.length ? `${activeRisks.length} issue${activeRisks.length===1?'':'s'} to review` : 'Model checks are controlled'}</h2></div><button onClick={()=>onNavigate('risks')}>Open risks</button></div><div className="bm-watch-list"><div><span>Cars and drivers</span><strong>{fleetCount} / {input.companyDriverCount}</strong><small>{driverGap<0?`${Math.abs(driverGap)} drivers missing`:'Fleet is covered'}</small></div><div><span>Daily capacity</span><strong>{num(output.totalDailyShipments)} shipments</strong><small>{shipmentsPerCar.toFixed(1)} per car</small></div><div><span>Fuel cost</span><strong>{money(output.fuelMonthlyCost)}</strong><small>{money(output.fuelMonthlyCost/26)} per working day</small></div></div></section></div>
    <MonthlyTotals input={input} output={output} fleetCount={fleetCount}/><details className="bm-detail-model"><summary>View detailed model and risk explanation</summary><Summary output={output} input={input} fleetCount={fleetCount} driverGap={driverGap} contribution={contribution} risks={risks} onNavigate={onNavigate}/></details></>;
}

function TrendChart({data}:{data:ReturnType<typeof buildProjection>}) { const width=680,height=230,pad=34; const max=Math.max(...data.flatMap(item=>[item.revenue,item.cost]),1); const point=(value:number,index:number)=>`${pad+index*(width-pad*2)/Math.max(1,data.length-1)},${height-pad-value/max*(height-pad*2)}`; const revenue=data.map((item,index)=>point(item.revenue,index)).join(' '); const cost=data.map((item,index)=>point(item.cost,index)).join(' '); return <section className="bm-panel bm-trend"><div className="bm-panel-head"><div><span>14-day operating trend</span><h2>Daily revenue against allocated cost</h2></div><div className="bm-legend"><i className="revenue"/> Revenue <i className="cost"/> Cost</div></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Fourteen day revenue and cost trend"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/><line x1={pad} y1={pad} x2={pad} y2={height-pad}/><polyline className="cost" points={cost}/><polyline className="revenue" points={revenue}/>{data.map((item,index)=><circle key={item.date} className={item.recorded?'recorded':'projected'} cx={point(item.revenue,index).split(',')[0]} cy={point(item.revenue,index).split(',')[1]} r="3"/>)}</svg><div className="bm-axis-labels"><span>{data[0]?.label}</span><span>{data.at(-1)?.label}</span></div><p>Projection uses the current monthly model. Save daily reports to replace projected revenue with recorded results.</p></section>; }
function CostChart({categories,total}:{categories:[string,number][];total:number}) { const labels:Record<string,string>={vehicleOwnership:'Vehicle rent',vehicleRunning:'Fuel & running',people:'People',facilities:'Facilities',perShipment:'Per shipment',other:'Other'}; return <section className="bm-panel bm-cost-chart"><div className="bm-panel-head"><div><span>Monthly cost composition</span><h2>Where {money(total)} is spent</h2></div></div><div className="bm-stacked-bar" aria-label="Monthly cost composition chart">{categories.map(([key,value],index)=><i key={key} className={`c${index}`} style={{width:`${value/Math.max(1,total)*100}%`}} title={`${labels[key]}: ${money(value)}`}/>)}</div><div className="bm-cost-legend">{categories.map(([key,value],index)=><div key={key}><i className={`c${index}`}/><span>{labels[key]}</span><strong>{money(value)}</strong><small>{(value/Math.max(1,total)*100).toFixed(1)}%</small></div>)}</div></section>; }
function Metric({label,value,tone}:{label:string;value:string;tone?:string}) { return <div className={tone??''}><span>{label}</span><strong>{value}</strong></div>; }
function DailyReport({input,output,records,setRecords}:{input:FinancialInput;output:ReturnType<typeof useSimulatedData>['financialOutput'];records:Record<string,DailyRecord>;setRecords:(value:Record<string,DailyRecord>|((previous:Record<string,DailyRecord>)=>Record<string,DailyRecord>))=>void}) {
  const today=toDateString(new Date());
  const empty=(date:string):DailyRecord=>({date,completedShipments:0,failedShipments:0,fuelLitres:Number((output.fuelMonthlyCost/26/Math.max(.01,input.fuelPricePerLiter)).toFixed(1)),driversPresent:input.companyDriverCount,notes:'',updatedAt:''});
  const [selectedDate,setSelectedDate]=useState(today);
  const [draft,setDraft]=useState<DailyRecord>(()=>records[today]??empty(today));
  const [message,setMessage]=useState('');
  const metrics=calculateDailyMetrics(draft,input,output);
  const update=(patch:Partial<DailyRecord>)=>setDraft(current=>({...current,...patch}));
  const selectDate=(date:string)=>{setSelectedDate(date);setDraft(records[date]??empty(date));setMessage('');};
  const save=()=>{const saved={...draft,date:selectedDate,updatedAt:new Date().toISOString()};setRecords(current=>({...current,[selectedDate]:saved}));setDraft(saved);setMessage('Daily report saved in this browser.');};
  const downloadPdf=async()=>{setMessage('Preparing PDF…');await exportDailyReportPdf(draft,input,output);setMessage('PDF downloaded.');};
  const downloadExcel=async()=>{setMessage('Preparing Excel workbook…');await exportBusinessModelExcel(draft,input,output);setMessage('Excel workbook downloaded.');};
  return <><div className="bm-page-head bm-summary-head"><div><h1>Daily operations report</h1><p>Record actual deliveries, failures, attendance, and fuel. Planned figures remain separate from what you enter.</p></div><label className="bm-date"><span>Report date</span><input aria-label="Report date" type="date" value={selectedDate} onChange={event=>selectDate(event.target.value)}/></label></div>
    <div className="bm-report-status"><span className={draft.updatedAt?'saved':'draft'}>{draft.updatedAt?'Recorded':'Draft—not recorded'}</span>{draft.updatedAt&&<small>Last saved {new Date(draft.updatedAt).toLocaleString('en-SA')}</small>}</div>
    <section className="bm-kpis"><Kpi label="Planned shipments" value={num(metrics.plannedShipments)}/><Kpi label="Completed" value={num(draft.completedShipments)}/><Kpi label="Completion rate" value={`${metrics.completionRate.toFixed(1)}%`} tone={metrics.recordedAttempts&&metrics.completionRate<95?'bad':'good'}/><Kpi label="Daily profit / loss" value={money(metrics.profit)} tone={metrics.profit<0?'bad':'good'}/></section>
    <div className="bm-two-col bm-report-grid"><section className="bm-form-card"><h2>Actual operations</h2><div className="bm-form-grid"><NumberInput label="Completed shipments" value={draft.completedShipments} onChange={value=>update({completedShipments:Number(value)})} suffix="shipments"/><NumberInput label="Failed shipments" value={draft.failedShipments} onChange={value=>update({failedShipments:Number(value)})} suffix="shipments"/><NumberInput label="Drivers present" value={draft.driversPresent} onChange={value=>update({driversPresent:Number(value)})} suffix={`of ${input.companyDriverCount}`}/><NumberInput label="Fuel used" value={draft.fuelLitres} onChange={value=>update({fuelLitres:Number(value)})} suffix="litres"/></div><label className="bm-notes"><span>Operations notes</span><textarea aria-label="Operations notes" value={draft.notes} onChange={event=>update({notes:event.target.value})} placeholder="Delays, vehicle issues, customer exceptions…"/></label><button className="bm-primary" onClick={save}><Check size={15}/> Save daily report</button></section>
      <section className="bm-panel"><h2>Daily financial calculation</h2><dl className="bm-facts"><div><dt>Recorded attempts</dt><dd>{num(metrics.recordedAttempts)}</dd></div><div><dt>Revenue</dt><dd>{money(metrics.revenue)}</dd></div><div><dt>Allocated company cost</dt><dd>{money(metrics.allocatedCost)}</dd></div><div><dt>Fuel cost from litres</dt><dd>{money(metrics.fuelCost)}</dd></div><div><dt>Profit / loss</dt><dd className={metrics.profit<0?'text-bad':''}>{money(metrics.profit)}</dd></div></dl><p className="bm-calculation-note">Allocated cost is monthly company cost ÷ 26 working days. Fuel is already included in allocated cost and shown separately for control—not added twice.</p></section></div>
    <section className="bm-panel bm-export-card"><div><span>Export current model</span><h2>Share the daily report or inspect all inputs</h2><p>PDF contains this daily report. Excel includes summary, daily report, company costs, cars and drivers, and customers.</p></div><div><button onClick={downloadPdf}><Download size={15}/> Export PDF</button><button onClick={downloadExcel}><Download size={15}/> Export Excel</button></div>{message&&<output aria-live="polite">{message}</output>}</section>
    <section className="bm-panel bm-report-history"><div className="bm-panel-head"><div><span>Recorded history</span><h2>Saved daily reports</h2></div></div>{Object.values(records).length?<div>{Object.values(records).sort((a,b)=>b.date.localeCompare(a.date)).map(record=><button key={record.date} onClick={()=>selectDate(record.date)}><span>{new Date(`${record.date}T12:00:00`).toLocaleDateString('en-SA',{dateStyle:'medium'})}</span><strong>{record.completedShipments} completed</strong><small>{record.failedShipments} failed</small></button>)}</div>:<p>No actual daily reports saved yet.</p>}</section></>;
}
function MonthlyTotals({input,output,fleetCount}:{input:FinancialInput;output:ReturnType<typeof useSimulatedData>['financialOutput'];fleetCount:number}) { const driverPayroll=fleetCount*input.driverSalary; const opsPayroll=input.opsTeamCount*input.opsTeamAvgSalary; const salesPayroll=input.salesTeamCount*input.salesTeamBaseSalary; const warehousePayroll=input.warehouseStaff*input.warehouseStaffSalary; const otherPeople=Math.max(0,output.costBreakdown.people-driverPayroll-opsPayroll-salesPayroll-warehousePayroll); const vehicleNonFuel=Math.max(0,output.fleetMonthlyCost-output.fuelMonthlyCost); const rows=[{label:'Drivers',formula:`${fleetCount} drivers × ${money(input.driverSalary)}`,total:driverPayroll},{label:'Operations team',formula:`${input.opsTeamCount} people × ${money(input.opsTeamAvgSalary)}`,total:opsPayroll},{label:'Sales team',formula:`${input.salesTeamCount} people × ${money(input.salesTeamBaseSalary)}`,total:salesPayroll},{label:'Warehouse staff',formula:`${input.warehouseStaff} people × ${money(input.warehouseStaffSalary)}`,total:warehousePayroll},{label:'Other people costs',formula:'Insurance and sales commission',total:otherPeople},{label:'Fuel',formula:`${fleetCount} cars at ${money(input.fuelPricePerLiter,2)} / litre`,total:output.fuelMonthlyCost},{label:'Cars: rent, insurance & maintenance',formula:`${fleetCount} cars`,total:vehicleNonFuel},{label:'Facilities & utilities',formula:'Warehouse, office, internet & electricity',total:output.costBreakdown.facilities},{label:'Per-shipment costs',formula:`${num(output.totalMonthlyShipments)} shipments / month`,total:output.costBreakdown.perShipment},{label:'Other company costs',formula:'Marketing, legal, software & miscellaneous',total:output.costBreakdown.other}]; return <section className="bm-panel bm-monthly-totals"><div className="bm-panel-head"><div><span>Monthly cost calculation</span><h2>What the company costs each month</h2></div><strong>{money(output.totalCost)}</strong></div><div className="bm-total-rows">{rows.map(row=><div key={row.label}><span><strong>{row.label}</strong><small>{row.formula}</small></span><b>{money(row.total)}</b></div>)}</div><div className="bm-total-result"><span><small>Total monthly revenue</small><strong>{money(output.totalRevenue)}</strong></span><span><small>Total monthly cost</small><strong>{money(output.totalCost)}</strong></span><span className={output.netMargin<0?'bad':'good'}><small>Monthly profit / loss</small><strong>{money(output.netMargin)}</strong></span></div></section>; }
function Summary({ output,input,fleetCount,driverGap,contribution,risks,onNavigate }: { output:ReturnType<typeof useSimulatedData>['financialOutput']; input:FinancialInput; fleetCount:number; driverGap:number; contribution:number; risks:{level:string;title:string;value:string;detail:string}[]; onNavigate:(view:View)=>void }) { const categories = Object.entries(output.costBreakdown).filter(([key]) => !['costPerShipment','total'].includes(key)) as [string,number][]; return <><div className="bm-page-head bm-summary-head"><div><h1>Business summary</h1><p>Current monthly result from the numbers entered in this app.</p></div><button onClick={() => onNavigate('costs')}><Settings2 size={15}/> Edit assumptions</button></div><section className="bm-kpis"><Kpi label="Monthly revenue" value={money(output.totalRevenue)} /><Kpi label="Monthly cost" value={money(output.totalCost)} /><Kpi label="Net result" value={money(output.netMargin)} tone={output.netMargin < 0 ? 'bad':'good'} /><Kpi label="Cost / shipment" value={money(output.costPerShipment,2)} /></section><div className="bm-two-col"><section className="bm-panel"><h2>Operating model</h2><dl className="bm-facts"><div><dt>Drivers</dt><dd><button onClick={() => onNavigate('drivers')}>{input.companyDriverCount}</button></dd></div><div><dt>Vehicles</dt><dd><button onClick={() => onNavigate('fleet')}>{fleetCount}</button></dd></div><div><dt>Shipments / day</dt><dd><button onClick={() => onNavigate('customers')}>{num(output.totalDailyShipments)}</button></dd></div><div><dt>Revenue / shipment</dt><dd>{money(output.avgRevenuePerShipment,2)}</dd></div><div><dt>Variable contribution / shipment</dt><dd>{money(contribution,2)}</dd></div><div><dt>Driver coverage</dt><dd className={driverGap < 0 ? 'text-bad':''}>{driverGap < 0 ? `${Math.abs(driverGap)} short` : `${driverGap} spare`}</dd></div></dl></section><section className="bm-panel"><h2>Cost breakdown</h2><div className="bm-cost-bars">{categories.map(([key,value]) => <div key={key}><span>{({vehicleOwnership:'Vehicle rent / ownership',vehicleRunning:'Vehicle running',people:'People',facilities:'Facilities',perShipment:'Per shipment',other:'Other'} as Record<string,string>)[key]}</span><i><b style={{width:`${Math.max(2,value/Math.max(1,output.totalCost)*100)}%`}} /></i><strong>{money(value)}</strong></div>)}</div></section></div><section className="bm-panel bm-summary-risks"><div className="bm-panel-head"><h2>Problems to fix</h2><button onClick={() => onNavigate('risks')}>View risk details</button></div>{risks.filter(r => r.level !== 'Controlled').map(risk => <div key={risk.title}><span>{risk.level}</span><strong>{risk.title}</strong><p>{risk.detail}</p></div>)}</section></>; }
function Kpi({label,value,tone}:{label:string;value:string;tone?:string}) { return <article className={tone ?? ''}><span>{label}</span><strong>{value}</strong></article>; }
// Draft-holding inputs: a null draft means "not editing" so the field always
// mirrors the external value (fleet-sync updates can never go stale). While
// the user is mid-edit their text wins until blur commits it.
function NumberInput({label,value,onChange,suffix,help}:{label:string;value:number;onChange:(value:string)=>void;suffix:string;help?:string}) { const [draft,setDraft]=useState<string|null>(null); const commit=()=>{if(draft===null)return;const parsed=Math.max(0,Number(draft)||0);onChange(String(parsed));setDraft(null);}; return <label className="bm-field"><span>{label}</span><div><input name={label.toLowerCase().replaceAll(' ','-')} type="number" min="0" inputMode="decimal" value={draft??String(value)} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();}} /><em>{suffix}</em></div>{help&&<small>{help}</small>}</label>; }
function Readout({label,value,tone}:{label:string;value:string;tone?:string}) { return <div className={`bm-readout ${tone??''}`}><span>{label}</span><strong>{value}</strong></div>; }
function EditableTable({columns,children}:{columns:string[];children:React.ReactNode}) { return <div className="bm-table-wrap"><div className="bm-table"><div className="bm-table-head">{columns.map((column,index)=><span key={`${column}-${index}`}>{column}</span>)}</div>{children}</div></div>; }
function TextInput({ariaLabel,value,onChange}:{ariaLabel:string;value:string;onChange:(value:string)=>void}) { return <input className="bm-cell-input" aria-label={ariaLabel} name={ariaLabel.toLowerCase().replaceAll(' ','-')} autoComplete="off" value={value} onChange={e=>onChange(e.target.value)} />; }
function CellNumber({ariaLabel,value,onChange,step='1'}:{ariaLabel:string;value:number;onChange:(value:number)=>void;step?:string}) { const [draft,setDraft]=useState<string|null>(null); const commit=()=>{if(draft===null)return;const parsed=Math.max(0,Number(draft)||0);onChange(parsed);setDraft(null);}; return <input className="bm-cell-input number" aria-label={ariaLabel} name={ariaLabel.toLowerCase().replaceAll(' ','-')} type="number" min="0" step={step} inputMode="decimal" value={draft??String(value)} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();}} />; }
function CostSections({input,output,setNumber,changeVehicle}:{input:FinancialInput;output:ReturnType<typeof useSimulatedData>['financialOutput'];setNumber:(field:NumberField,value:string)=>void;changeVehicle:(id:string,patch:Partial<VehicleClass>)=>void}) { const groups:{title:string;fields:[string,NumberField,string][]}[]=[{title:'People',fields:[['Driver salary','driverSalary','SAR / driver / month'],['Operations team', 'opsTeamCount','people'],['Average operations salary','opsTeamAvgSalary','SAR / month'],['Sales team','salesTeamCount','people'],['Average sales salary','salesTeamBaseSalary','SAR / month'],['Warehouse staff','warehouseStaff','people'],['Warehouse staff salary','warehouseStaffSalary','SAR / month']]},{title:'Facilities & systems',fields:[['Warehouse rent','warehouseRent','SAR / month'],['Warehouse utilities','warehouseUtilities','SAR / month'],['Office rent','officeRent','SAR / month'],['Internet','internetCost','SAR / month'],['Electricity','electricityCost','SAR / month'],['Software','technologySaaS','SAR / month']]},{title:'Per shipment & risk',fields:[['Packaging','packagingCostPerUnit','SAR / shipment'],['Pick and pack','pickPackLaborPerOrder','SAR / shipment'],['Labels and documents','labelsAndDocs','SAR / shipment'],['Return handling','returnLogisticsCost','SAR / return'],['Failed delivery rate','failedDeliveryRate','%'],['Failed delivery cost','failedDeliveryCost','SAR / failure'],['Return rate','returnRate','%'],['Customer payment delay','clientPaymentDelay','days']]},{title:'Other monthly costs',fields:[['Marketing','marketingBudget','SAR / month'],['Accounting and legal','accountingLegal','SAR / month'],['Miscellaneous','miscExpenses','SAR / month']]}]; return <div className="bm-cost-sections"><section className="bm-form-card"><h2>Vehicles & fuel</h2><div className="bm-form-grid bm-fuel-grid"><NumberInput label="Fuel price" value={input.fuelPricePerLiter} onChange={value=>setNumber('fuelPricePerLiter',value)} suffix="SAR / litre" /><Readout label="Calculated fuel cost / month" value={money(output.fuelMonthlyCost)} /><Readout label="Total fleet cost / month" value={money(output.fleetMonthlyCost)} /></div><EditableTable columns={['Vehicle type','Quantity','Rent / vehicle / month','Insurance + maintenance','Fuel use / 100 km','Distance / day']}>
    {input.vehicleClasses.map(vehicle=><div className="bm-table-row bm-cost-vehicle-row" key={vehicle.id}><strong>{vehicle.name}</strong><span>{vehicle.quantity}</span><CellNumber ariaLabel={`${vehicle.name} rent cost`} value={vehicle.monthlyRent} onChange={value=>changeVehicle(vehicle.id,{monthlyRent:value})}/><CellNumber ariaLabel={`${vehicle.name} insurance and maintenance cost`} value={vehicle.variableCost} onChange={value=>changeVehicle(vehicle.id,{variableCost:value})}/><CellNumber ariaLabel={`${vehicle.name} fuel consumption`} value={vehicle.fuelEfficiency} step="0.1" onChange={value=>changeVehicle(vehicle.id,{fuelEfficiency:value})}/><CellNumber ariaLabel={`${vehicle.name} daily distance`} value={vehicle.avgDailyDistance} onChange={value=>changeVehicle(vehicle.id,{avgDailyDistance:value})}/></div>)}
  </EditableTable></section>{groups.map(group=><section className="bm-form-card" key={group.title}><h2>{group.title}</h2><div className="bm-form-grid">{group.fields.map(([label,field,suffix])=><NumberInput key={field} label={label} value={Number(input[field]??0)} onChange={value=>setNumber(field,value)} suffix={suffix}/>)}</div></section>)}</div>; }
